config/routes.rb
Rails.application.routes.draw do
  # OmniAuth
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  resources :sessions, only: [:create, :destroy]
  # User Dashboard
  resources :dashboards, :only => [:show]
  # News
  root to: 'news#index'
  resources :news, :only => [:index]
  get '/congressional-report', to: 'news#congressional_report'
  get 'article', to: 'news#show_article', as: 'show_article'
  get 'download/article', to: 'news#download_pdf', as: 'download_pdf'
  # Business
  resources :businesses, :only => [:index]
  post '/businesses', to: 'businesses#find_businesses'
  # Uber
  resources :ubers, :only => [:index]
  # Conversations
  resources :conversations do
    resources :responses, :except => [:index, :show]
  end
  # Pages
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  include ApiHelper
  skip_before_action :require_authentication!
  def index
    if cookies[:lat_lng]
      @lat_lng = cookies[:lat_lng].split("|")
      puts @lat_lng.inspect
    end
  end

  def find_businesses
    if @found_businesses = JSON.parse(get_businesses(search_params))
      @businesses = @found_businesses['businesses']
    else
      puts 'Yelp Businesses not retrived. (BusinessesController#Find_Businesses)'
    end
    respond_to do |format|
      format.html { redirect_to businesses_path }
      format.js
    end
  end

  private
  def search_params
    params.permit(:term, :location, :price_point)
  end
end

app/views/businesses/_businesses.html.erb
<h3 class="text-center">Here are your results:</h3>
<div id="overflow-business">
  <% @businesses.in_groups_of(3, false).each do |company| %>
    <div class="row">
      <% company.each do |business| %>
        <div class="card col-md-4 col-sm-4">
          <%= image_tag(business['image_url'], alt: business['name'], class: 'business-img') %>
          <h4 class="card-title"><%= business['name'] %></h4>
          <p class="card-text"><%= business['location']['address1'] %>, <%= business['location']['city'] %>, <%= business['location']['state'] %></p>
          <%= link_to 'Let\'s go!', ubers_path(longitude: business['coordinates']['longitude'], latitude: business['coordinates']['latitude'], name: business['name']), class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/businesses/_page-title.html.erb
<% title 'Businesses' %>

app/views/businesses/find_businesses.js.erb
$(".businesses").html("<%= j render 'businesses' %>");

app/views/businesses/index.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Yelp &amp; Uber</h1>
    <p class="lead text-muted">Search for Businesses through Yelp and book an Uber to get you there.</p>
  </div>
</section>
<br>
<div class="container">
  <%= bootstrap_form_tag remote: true do |f| %>
    <%= f.text_field :term, placeholder: 'Tacos', required: true %><br>
    <%= f.text_field :location, placeholder: 'Portland', required: true %><br>
    <%= f.text_field :price_point, placeholder: '(Optional) Up to four $ signs, ex: $$' %><br>
    <%= f.submit "Search" %>
  <% end %>

  <div class="businesses">

  </div>
</div>
<% unless @lat_lng %>
<script>
  getGeoLocation();
</script>
<% end %>
<%= render 'page-title' %>