config/routes.rb
Rails.application.routes.draw do
  # OmniAuth
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  resources :sessions, only: [:create, :destroy]
  # User Dashboard
  resources :dashboards, :only => [:show]
  # News
  root to: 'news#index'
  resources :news, :only => [:index]
  get '/congressional-report', to: 'news#congressional_report'
  get 'article', to: 'news#show_article', as: 'show_article'
  get 'download/article', to: 'news#download_pdf', as: 'download_pdf'
  # Business
  resources :businesses, :only => [:index]
  post '/businesses', to: 'businesses#find_businesses'
  # Uber
  resources :ubers, :only => [:index]
  # Conversations
  resources :conversations do
    resources :responses, :except => [:index, :show]
  end
  # Pages
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
    belongs_to :user
    has_many :responses
    validates :title, presence: true, length: { minimum: 3, maximum: 20}
    validates :content, presence: true, length: { minimum: 10, maximum: 300}
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :require_authentication!, :except => [:index, :show]
  before_action :set_conversation, :only => [:show, :destroy, :edit, :update]
  def index
    @conversations = Conversation.all
  end

  def new
    @conversation = current_user.conversations.new
  end

  def create
    @conversation = current_user.conversations.new(conversation_params)
    if @conversation.save
      # Make Async
      redirect_to conversation_path(@conversation)
      flash[:success] = 'You\'ve Started a Conversation!'
    else
      render :new
    end
  end

  def edit
    # create a column for edited? == boolean, to show 'this post has been edited'
  end

  def update
    if @conversation.update(conversation_params)
      redirect_to conversation_path(@conversation)
      flash[:success] = 'Conversation successfully updated'
    else
      render :edit
    end
  end

  def show
    @response = Response.new
  end

  def destroy
    @conversation.destroy
    flash[:danger] = 'Conversation was successfully deleted'
    redirect_to conversations_path
  end

  private
  def conversation_params
    params.require(:conversation).permit(:title, :content)
  end

  def set_conversation
    @conversation = Conversation.find(params[:id])
  end
end

app/views/conversations/_form.html.erb
<%= render "layouts/errors", :object => @conversation %>

<%= bootstrap_form_for @conversation do |f| %>
  <%= f.text_field :title, class: 'form-control' %>
  <%= f.text_area :content, class: 'form-control' %>
  <%= f.submit "Start Conversation" %>
<% end %>

app/views/conversations/_page-title.html.erb
<% title 'Conversations' %>

app/views/conversations/create.js.erb
alert('works!');
toastr.success('Success!', 'You\'ve started a Conversation!')

app/views/conversations/edit.html.erb
<h1>Edit <%= @conversation.title %></h1>
<%= render 'form' %>
<%= render 'page-title' %>

app/views/conversations/index.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Conversations</h1>
    <p class="lead text-muted">News, Politics, Businesses, Meetups talks</p>
    <p>
      <%= link_to 'Start a New Conversation', new_conversation_path, class: 'btn btn-outline-primary btn-sm' %>
    </p>
  </div>
</section>

<div class="container">
  <div class="row conversations-bar-main">
    <div class="col-md-4">
      Conversation Title
    </div>
    <div class="col-md-4">
      Conversation Author
    </div>
    <div class="col-md-4">
      Date Posted
    </div>
  </div>

  <% @conversations.each do |conversation| %>
    <div class="<%= cycle('conversations-bar1', 'conversations-bar2') %> row">
      <div class="col-md-4">
        <%= link_to conversation.title, conversation_path(conversation) %>
      </div>
      <div class="col-md-4">
        <%= link_to conversation.user.name, dashboard_path(conversation.user.dashboard) %>
      </div>
      <div class="col-md-4">
        <%= distance_of_time_in_words(conversation.created_at, Time.now) %> ago
      </div>
    </div>
  <% end %>
</div>

<%= render 'page-title' %>

app/views/conversations/new.html.erb
<div class="container">
  <h1>Start a Conversation</h1>

  <div id="new-conversation">
    <%= render 'form' %>
  </div>
  <%= render 'page-title' %>
</div>

app/views/conversations/show.html.erb
<%= render 'page-title' %>

<div class="container">
  <br>
  <% if current_user && current_user.id == @conversation.user.id %>
  <div class="conversation-buttons">
    <%= link_to 'Delete', conversation_path, method: :delete, :data => {confirm: 'Delete the entire Conversation?'}, class: 'btn btn-danger btn-sm' %>
    <%= link_to 'Edit', edit_conversation_path(@conversation), class: 'btn btn-warning btn-sm' %>
  </div>
  <% end %>
  <br>
  <div class="col-md-12">
      <div class="panel panel-white post panel-shadow">
          <div class="post-heading">
              <div class="pull-left image">
                  <%= link_to dashboard_path(@conversation.user.dashboard) do %>
                     <%= image_tag "http://api.adorable.io/avatar/200/#{@conversation.user.id}", class: 'avatar' %>
                  <% end %>
              </div>
              <div class="pull-left meta">
                  <div class="title h5">
                      <a href="#"><b><%= link_to @conversation.user.name, dashboard_path(@conversation.user.dashboard) %></b></a>
                      made a post: <%= @conversation.title %>
                  </div>
                  <h6 class="text-muted time"><%= distance_of_time_in_words(@conversation.created_at, Time.now) %> ago</h6>
              </div>
          </div>
          <div class="post-description">
              <p><%= @conversation.content %></p>
              <!-- thumbs up <div class="stats">
                  <a href="#" class="btn btn-default stat-item">
                      <i class="fa fa-thumbs-up icon"></i>2
                  </a>
                  <a href="#" class="btn btn-default stat-item">
                      <i class="fa fa-share icon"></i>12
                  </a>
              </div> -->
          </div>
          <div class="post-footer">
            <% if current_user %>
              <%= render 'responses/form' %>
            <% end %>
            <ul class="comments-list">
              <% @conversation.responses.each do |response| %>
              <li class="comment">
                <%= link_to dashboard_path(response.user.dashboard), class: 'pull-left' do %>
                   <%= image_tag "http://api.adorable.io/avatar/200/#{response.user.id}", class: 'avatar' %>
                <% end %>
                  <div class="comment-body">
                    <div class="comment-heading">
                        <h4 class="user"><%= link_to response.user.name, dashboard_path(response.user.dashboard) %></h4>
                        <h5 class="time"><%= distance_of_time_in_words(response.created_at, Time.now) %></h5>
                    </div>
                    <p><%= response.content %></p>
                  </div>
                </li>
                <% end %>
                  <!-- responses to responses <ul class="comments-list">
                      <li class="comment">
                          <a class="pull-left" href="#">
                              <img class="avatar" src="http://api.adorable.io/avatar/200/7" alt="avatar">
                          </a>
                          <div class="comment-body">
                              <div class="comment-heading">
                                  <h4 class="user">Ryan Haywood</h4>
                                  <h5 class="time">3 minutes ago</h5>
                              </div>
                              <p>Relax my friend</p>
                          </div>
                      </li>
                      <li class="comment">
                          <a class="pull-left" href="#">
                              <img class="avatar" src="http://api.adorable.io/avatar/200/5" alt="avatar">
                          </a>
                          <div class="comment-body">
                              <div class="comment-heading">
                                  <h4 class="user">Gavino Free</h4>
                                  <h5 class="time">3 minutes ago</h5>
                              </div>
                              <p>Ok, cool.</p>
                          </div>
                      </li>
                  </ul> -->
              </ul>
          </div>
      </div>
  </div>
</div>