config/routes.rb
Rails.application.routes.draw do
  # OmniAuth
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  resources :sessions, only: [:create, :destroy]
  # User Dashboard
  resources :dashboards, :only => [:show]
  # News
  root to: 'news#index'
  resources :news, :only => [:index]
  get '/congressional-report', to: 'news#congressional_report'
  get 'article', to: 'news#show_article', as: 'show_article'
  get 'download/article', to: 'news#download_pdf', as: 'download_pdf'
  # Business
  resources :businesses, :only => [:index]
  post '/businesses', to: 'businesses#find_businesses'
  # Uber
  resources :ubers, :only => [:index]
  # Conversations
  resources :conversations do
    resources :responses, :except => [:index, :show]
  end
  # Pages
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  include ApiHelper
  skip_before_action :require_authentication!
  # TODO: Remove else and return data from the API method's call or rescue
  def index
    if @top_guardian_headlines = retrieve_guardian_headlines
      @top_guardian_headlines = JSON.parse(@top_guardian_headlines)['response']['results']
    else
      # retrieve from cache
      puts 'Top Guardian Headlines not retrieved (NewsController#Index)'
    end

    if @nyt_home_articles = retrieve_home_articles
      @nyt_home_articles = JSON.parse(@nyt_home_articles)['results']
    else
      # retrieve from cache
      puts 'NYT Home Articles not retrieved (NewsController#Index)'
    end
  end

  def show_article
    @article = params[:article]
    if @article
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    end
  end

  def congressional_report
    if @reports = retrieve_congressional_bills
      @reports = JSON.parse(@reports)['results'][0]['bills']
      else
        # retrieve from cache
        puts 'Propublica Recent Bills Passed by Senate not retrieved (NewsController#Congressional_Report)'
      end
  end

  def download_pdf
    send_data(generate_pdf(params[:headline], params[:author], params[:section], params[:date], params[:body]), :filename => "article.pdf", :type => "application/pdf")
  end

  private
  def generate_pdf(headline, author, section, date, body)
    Prawn::Document.new do
      text "#{headline}", align: :center, size: 18
      text "#{section}", align: :center, size: 18
      text "#{author}",   align: :center, size: 14
      text "#{date}",   align: :center, size: 12
      move_down 12

      column_box([0, cursor], columns: 1, width: bounds.width) do
          text((<<-END.gsub(/\s+/, ' ') + "\n\n"))
            Abstract: #{body}
          END
        end
      text "Courtesy of the New York Times.",   align: :center, size: 12
      end.render
  end

end

app/views/news/_article.html.erb
<div class="art-wrapper">
  <a href="#" class="close" data-dismiss="art-wrapper">&#215;</a>
  <h2><%= @article['title'] %> | <%= @article['section'] %></h2>
  <h6><%= @article['byline'] %></h6>
  <%= link_to 'Print Summary', download_pdf_path(headline: @article['title'], author: @article['byline'], section: @article['section'], date: @article['published_date'].to_date.strftime("%d %B %Y"), body: @article['abstract']), target: :_blank %>
  <h5><%= @article['published_date'].to_date.strftime("%d %B %Y") %></h5>
  <% if @article['multimedia'][2] %>
  <%= image_tag(@article['multimedia'][2]['url']) %>
  <h5><%= @article['multimedia'][2]['caption'] %></h5>
  <% end %>
  <h4>Abstract:</h4>
  <p><%= @article['abstract'] %><p>
  <p><%= link_to 'Original', @article['url'] %></p>
</div>

app/views/news/congressional_report.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">House &amp; Senate</h1>
    <p class="lead text-muted">Your Daily Congressional Report</p>
  </div>
</section>
<br>

<div class="container text-center">
  <% if @reports %>
    <% @reports.each do |bill| %>
    <div class="card col-md-12">
      <%= image_tag ('propublica/'.concat((rand(1...9)).to_s).concat('.jpg')), :class => 'rounded mx-auto d-block', size: "210x140"  %>
      <p class="card-title"><%= bill['number'] %> <%= bill['title'] %></p>
      <p class="card-text">Introduced: <%= bill['introduced_date'] %></p>
      <% if !bill['primary_subject'].empty? %>
        <p class="card-text">Subject: <%= bill['primary_subject'] %></p>
      <% end %>
      <p class="card-text">Last Major Action: <%= bill['latest_major_action'] %></p>
      <p class="card-text"><%= link_to 'See Bill', bill['govtrack_url'] %></p>
    </div>
    <% end %>
  <% end %>
</div>

app/views/news/index.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">News Center</h1>
    <p class="lead text-muted">Featuring the latest stories from the New York Times and The Guardian News</p>
  </div>
</section>

<div class="container">
  <br>
  <div class="row">
    <div class="col-md-6">
      <% if @nyt_home_articles %>
        <% @nyt_home_articles.each do |article| %>
        <div class="card col-md-12">
          <h5 class="card-title"><%= article['title'] %> | <%= article['section'] %></h5>
          <h6 class="card-text"><%= article['byline'] %></h6>
          <h5 class="card-text"><%= article['published_date'].to_date.strftime("%d %B %Y") %></h5>
          <% if article['multimedia'][3] %>
            <%= image_tag article['multimedia'][3]['url'], class: 'nyt-dashboard-img center-block' %>
            <p class="card-text"><%= article['multimedia'][3]['caption'] %></p>
          <% elsif article['multimedia'][2] %>
            <%= image_tag article['multimedia'][2]['url'], class: 'nyt-dashboard-img center-block' %>
            <p class="card-text"><%= article['multimedia'][2]['caption'] %></p>
          <% end %>
          <p class="card-text"><%= link_to 'View Information', show_article_path(article: article), remote: true %></p>
          <p class="card-text"><%= link_to 'Original Story', article['url'], target: '_blank' %></p>
        </div>
        <% end %>
      <% end %>
    </div>
    <div class="col-md-6">
      <% if @top_guardian_headlines %>
        <% @top_guardian_headlines.each do |article| %>
          <div class="card col-md-12">
            <h5 class="card-title"><%= article['webTitle'] %> | <%= article['sectionName'] %></h5>
            <h5 class="card-text"><%= article['webPublicationDate'].to_date.strftime("%d %B %Y") %></h5>
            <p class="card-text"><%= link_to 'Original Story', article['webUrl'], target: '_blank' %></p>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/news/show_article.js.erb
$(".art-wrapper").remove();

<% if @article %>
  $("body").append("<%= j render('article') %>");
  toastr.success('Article Successfully Generated!');
<% else %>
  toastr.error('Something went wrong.', 'Whoa!');
<% end %>