config/routes.rb
Rails.application.routes.draw do
  # OmniAuth
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  resources :sessions, only: [:create, :destroy]
  # User Dashboard
  resources :dashboards, :only => [:show]
  # News
  root to: 'news#index'
  resources :news, :only => [:index]
  get '/congressional-report', to: 'news#congressional_report'
  get 'article', to: 'news#show_article', as: 'show_article'
  get 'download/article', to: 'news#download_pdf', as: 'download_pdf'
  # Business
  resources :businesses, :only => [:index]
  post '/businesses', to: 'businesses#find_businesses'
  # Uber
  resources :ubers, :only => [:index]
  # Conversations
  resources :conversations do
    resources :responses, :except => [:index, :show]
  end
  # Pages
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>

    <p>News Content Courtesy of <b>The New York Times</b> and <b>The Guardian</b>.</p>

    <p>Political Content Courtesy of <b>Propublica</b>. Business Search Courtesy of <b>Yelp</b>.</p>

    <p>
      <ol class="list-unstyled social-links">
        <li><a href="https://github.com/JPCodes"><%= fa_icon "github" %></a></li>
        <li><a href="https://twitter.com/jp_codes"><%= fa_icon "twitter" %></a></li>
        <li><a href="https://www.linkedin.com/in/jpcodes/"><%= fa_icon "linkedin-square" %></a></li>
      </ol>
    </p>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class='alert alert-<%="#{name}"%>'>
    <a href="#" class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, msg, :id => 'flash_#{name}' if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/_nav.html.erb
<div class="collapse bg-inverse" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 py-4">
        <h4 class="text-white">The Commuter</h4>
        <p class="text-muted">The Commuter is the app that I wish I had during my morning commute. It features news from the New York Times and the Guardian. There is also a section for viewing the latest major bills in Congress and their current status. <b>Users can also customize their dashboard by choosing what news they'd like to see.</b> If one wishes to discuss any of these things, there is also a discussion forum that is available to anyone that signs in using Google or Facebook. Lastly, there is a page that features a Yelp search and allows the user to see any search result through the Uber app.</p>
      </div>
      <div class="col-sm-4 py-4">
        <h4 class="text-white">Menu</h4>
        <ul class="list-unstyled">
          <li><%= link_to 'Home', root_path, class: 'text-white' %></li>
          <!-- TODO: Replace user check with null object pattern and allow guest user to see a sample dashboard -->
          <% if current_user %>
          <li><%= link_to 'Dashboard - New!', dashboard_path(current_user.dashboard) %></li>
          <% end %>
          <li><%= link_to 'Business Search', businesses_path, class: 'text-white' %></li>
          <li><%= link_to 'Congressional Report', congressional_report_path, class: 'text-white' %></li>
          <li><%= link_to 'Conversations', conversations_path, class: 'text-white' %></li>
          <li><%= link_to 'About The Commuter', about_path, class: 'shameless-plug' %></li>
          <li><%= link_to 'Contact the Developer', contact_path, class: 'shameless-plug' %></li>
          <% if current_user %>
          Signed in as <strong><%= current_user.name %></strong>!
          <li><%= link_to "Sign out", signout_path, id: "sign_out" %></li>
          <% else %>
          <li><%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %></li>
          <li><%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="navbar navbar-inverse bg-inverse">
  <div class="container d-flex justify-content-between">
    <%= link_to 'The Commuter', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Commuter | <%= content_for?(:title) ? yield(:title) : 'News & Politics' %></title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/nav' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-98995906-1', 'auto');
      ga('send', 'pageview');
    </script>
  </body>
</html>